/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CoreEvidenceInterface extends ethers.utils.Interface {
  functions: {
    "addEvidenceDelegate(address)": FunctionFragment;
    "delegateeExists(address)": FunctionFragment;
    "evidenceExists(address)": FunctionFragment;
    "evidences(address)": FunctionFragment;
    "getEvidence(address)": FunctionFragment;
    "numEvidences()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "submitEvidence(address,uint256,bytes32)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addEvidenceDelegate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateeExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceExists",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "evidences", values: [string]): string;
  encodeFunctionData(functionFragment: "getEvidence", values: [string]): string;
  encodeFunctionData(
    functionFragment: "numEvidences",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEvidenceDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegateeExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "evidences", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numEvidences",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Delegated(address,address)": EventFragment;
    "EvidenceAdded(address,address,uint256,bytes32)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Delegated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EvidenceAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class CoreEvidence extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CoreEvidenceInterface;

  functions: {
    addEvidenceDelegate(
      newEvidenceDelegate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addEvidenceDelegate(address)"(
      newEvidenceDelegate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    delegateeExists(
      delegatee: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "delegateeExists(address)"(
      delegatee: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    evidenceExists(user: string, overrides?: CallOverrides): Promise<[boolean]>;

    "evidenceExists(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    evidences(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string] & {
        user: string;
        delegatee: string;
        timestamp: BigNumber;
        evidence: string;
      }
    >;

    "evidences(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string] & {
        user: string;
        delegatee: string;
        timestamp: BigNumber;
        evidence: string;
      }
    >;

    getEvidence(
      user: string,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, string]>;

    "getEvidence(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, string]>;

    numEvidences(overrides?: CallOverrides): Promise<[number]>;

    "numEvidences()"(overrides?: CallOverrides): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    submitEvidence(
      user: string,
      timestamp: BigNumberish,
      evidence: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "submitEvidence(address,uint256,bytes32)"(
      user: string,
      timestamp: BigNumberish,
      evidence: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  addEvidenceDelegate(
    newEvidenceDelegate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addEvidenceDelegate(address)"(
    newEvidenceDelegate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  delegateeExists(
    delegatee: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "delegateeExists(address)"(
    delegatee: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  evidenceExists(user: string, overrides?: CallOverrides): Promise<boolean>;

  "evidenceExists(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  evidences(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, string] & {
      user: string;
      delegatee: string;
      timestamp: BigNumber;
      evidence: string;
    }
  >;

  "evidences(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, string] & {
      user: string;
      delegatee: string;
      timestamp: BigNumber;
      evidence: string;
    }
  >;

  getEvidence(
    user: string,
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber, string]>;

  "getEvidence(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber, string]>;

  numEvidences(overrides?: CallOverrides): Promise<number>;

  "numEvidences()"(overrides?: CallOverrides): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  submitEvidence(
    user: string,
    timestamp: BigNumberish,
    evidence: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "submitEvidence(address,uint256,bytes32)"(
    user: string,
    timestamp: BigNumberish,
    evidence: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addEvidenceDelegate(
      newEvidenceDelegate: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addEvidenceDelegate(address)"(
      newEvidenceDelegate: string,
      overrides?: CallOverrides
    ): Promise<void>;

    delegateeExists(
      delegatee: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "delegateeExists(address)"(
      delegatee: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    evidenceExists(user: string, overrides?: CallOverrides): Promise<boolean>;

    "evidenceExists(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    evidences(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string] & {
        user: string;
        delegatee: string;
        timestamp: BigNumber;
        evidence: string;
      }
    >;

    "evidences(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string] & {
        user: string;
        delegatee: string;
        timestamp: BigNumber;
        evidence: string;
      }
    >;

    getEvidence(
      user: string,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, string]>;

    "getEvidence(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, string]>;

    numEvidences(overrides?: CallOverrides): Promise<number>;

    "numEvidences()"(overrides?: CallOverrides): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    submitEvidence(
      user: string,
      timestamp: BigNumberish,
      evidence: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "submitEvidence(address,uint256,bytes32)"(
      user: string,
      timestamp: BigNumberish,
      evidence: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Delegated(owner: string | null, delegatee: string | null): EventFilter;

    EvidenceAdded(
      user: string | null,
      delegatee: string | null,
      timestamp: null,
      evidence: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    addEvidenceDelegate(
      newEvidenceDelegate: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addEvidenceDelegate(address)"(
      newEvidenceDelegate: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    delegateeExists(
      delegatee: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "delegateeExists(address)"(
      delegatee: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    evidenceExists(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "evidenceExists(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    evidences(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "evidences(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEvidence(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getEvidence(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numEvidences(overrides?: CallOverrides): Promise<BigNumber>;

    "numEvidences()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    submitEvidence(
      user: string,
      timestamp: BigNumberish,
      evidence: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "submitEvidence(address,uint256,bytes32)"(
      user: string,
      timestamp: BigNumberish,
      evidence: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addEvidenceDelegate(
      newEvidenceDelegate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addEvidenceDelegate(address)"(
      newEvidenceDelegate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    delegateeExists(
      delegatee: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "delegateeExists(address)"(
      delegatee: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    evidenceExists(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "evidenceExists(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    evidences(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "evidences(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEvidence(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getEvidence(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numEvidences(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "numEvidences()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    submitEvidence(
      user: string,
      timestamp: BigNumberish,
      evidence: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "submitEvidence(address,uint256,bytes32)"(
      user: string,
      timestamp: BigNumberish,
      evidence: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
